- name: Copy Mysql settings
  copy: src="my.cnf" dest="/etc/my.cnf" owner=root mode=0644

- name: Change Mysql password
  template: src="changepassword.sql.j2" dest="/tmp/changepassword.sql" owner=root mode=0744

- name: Copy initdb script
  template: src="initdb.sh.j2" dest="/root/initdb.sh" owner=root mode=0744

- name: Start mysql
  service: name=mysql state=started

- name: Initialize mysql db
  script: /root/initdb.sh

